---
- name:
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
    docker_daemon_options:
      insecure-registries : ["192.168.56.115:8082"]
  pre_tasks:
    - name: Install packages
      package:
        name:
          - unzip
          - net-tools
        state: present
    - name: Create panda group
      group:
        name: panda
        state: present

    - name: Create panda user belonging to sudo and panda groups
      user:
        name: panda
        shell: /bin/bash
        groups:
          - panda
          - sudo

    - name: Set authorized key for user panda copying it from vagrant user
      authorized_key:
        user: panda
        state: present
        key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"


    - name: Create .ssh directory for user panda
      file:
        path: /home/panda/.ssh
        state: directory
        owner: panda
        group: panda
        mode: 0700

    - name: Copy id_rsa_git key for user panda
      copy:
        src: /vagrant/PandaCore/panda-ssh
        dest: /home/panda/.ssh/id_rsa_git
        owner: panda
        group: panda
        mode: 0600

    - name: Configure SSH config file for user panda
      blockinfile:
        path: /home/panda/.ssh/config
        block: |
          Host github.com
            IdentityFile /home/panda/.ssh/id_rsa_git
            StrictHostKeyChecking no
        owner: panda
        group: panda
        mode: 0644
        create: yes

    - name: Ensure panda has access to .ansible/tmp directory
      ansible.builtin.file:
        path: /home/panda/.ansible/tmp
        state: directory
        mode: '0770'
        owner: panda
        group: panda
      become: true

    - name: Change to panda user directory
      ansible.builtin.shell:
        cmd: cd /home/panda
      args:
        executable: /bin/bash

  roles:
    - geerlingguy.docker
    - deekayen.awscli2
    - diodonfrost.terraform
    - packages
    - infrastructure
